stages:
  - lint
  - test
  - build

image: python:3.6-slim


flake8:
  stage: lint
  script:
    - pip install -r requirements/dev.txt
    - flake8

pytest:
  stage: test
  script:
    - pip install -r requirements/dev.txt
    - pytest

build-testpypi-packages:
  stage: build
  only:
    - master
    - /^release\/.*$/
  script:
    - bin/gen-pypirc
    - bin/gen-devver
    - pip install -r requirements/packaging.txt
    - python setup.py sdist bdist_wheel
    - twine upload -r testpypi dist/*

build-docker-image:
  stage: build
  only:
    - master
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/attakei-lab/yagura:latest .
    - docker push registry.gitlab.com/attakei-lab/yagura:latest
