stages:
  - lint
  - test
  - build

image: python:3.6-slim


flake8:
  stage: lint
  script:
    - pip install -r requirements/lint.txt
    - flake8

pytest:
  stage: test
  script:
    - pip install -r requirements.txt -r requirements/test.txt
    - pytest

build-testpypi-packages:
  stage: build
  only:
    - master
    - /^release\/.*$/
  script:
    - tools/gen_pypirc
    - tools/gen_dev_ver
    - pip install -r requirements/packaging.txt
    - python setup.py sdist bdist_wheel
    - twine upload -r testpypi dist/*

