stages:
  - lint
  - test
  - build

image: python:3.6-slim


flake8:
  stage: lint
  script:
    - pip install -r requirements/lint.txt
    - flake8

pytest:
  stage: test
  script:
    - pip install -r requirements.txt -r requirements/test.txt
    - pytest

