stages:
  - lint
  - test
  - build

image: python:3.6-slim


flake8:
  stage: lint
  script:
    - pip install -r requirements/dev.txt
    - flake8

pytest:
  stage: test
  script:
    - pip install -r requirements/dev.txt
    - pytest


build-testpypi-packages:
  stage: build
  only:
    - master
    - /^release\/.*$/
  script:
    - if [ "$CI_PROJECT_NAMESPACE" != "attakei" ] ; then exit 0; fi
    - bin/gen-pypirc
    - bin/gen-devver
    - pip install -r requirements/packaging.txt -r requirements.txt
    - apt-get update
    - apt-get install -y gettext
    - python manage.py compilemessages
    - python setup.py sdist bdist_wheel
    - twine upload -r testpypi dist/*

build-docker-image:
  stage: build
  only:
    - master
    - /^release\/.*$/
  image: docker:latest
  services:
    - docker:dind
  script:
    - if [ "$CI_PROJECT_NAMESPACE" != "attakei" ] ; then exit 0; fi
    - |
      if [ "$CI_COMMIT_REF_NAME" = "master" ] ; then
        IMAGE_TAG="latest"
      else
        IMAGE_TAG=${CI_COMMIT_REF_NAME/\//-}
      fi
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/attakei/yagura:$IMAGE_TAG .
    - docker push registry.gitlab.com/attakei/yagura:$IMAGE_TAG

build-public-docker-image:
  stage: build
  only:
    - tags
  image: docker:latest
  services:
    - docker:dind
  script:
    - if [ "$CI_PROJECT_NAMESPACE" != "attakei" ] ; then exit 0; fi
    - IMAGE_TAG=${CI_COMMIT_REF_NAME/\//-}
    - docker build -t attakei/yagura:$IMAGE_TAG .
    - docker build -t attakei/yagura:$IMAGE_TAG-mysqlclient --build-arg USE_MYSQLCLIENT=1 .
    - echo $DOCKER_HUB_TOKEN | docker login -u attakei --password-stdin
    - docker push attakei/yagura

build-pypi-packages:
  stage: build
  only:
    - tags
  script:
    - if [ "$CI_PROJECT_NAMESPACE" != "attakei" ] ; then exit 0; fi
    - bin/gen-pypirc
    - pip install -r requirements/packaging.txt -r requirements.txt
    - apt-get update
    - apt-get install -y gettext
    - python manage.py compilemessages
    - python setup.py sdist bdist_wheel
    - twine upload dist/*

build-docker-tagged-image:
  stage: build
  only:
    - tags
  image: docker:latest
  services:
    - docker:dind
  script:
    - if [ "$CI_PROJECT_NAMESPACE" != "attakei" ] ; then exit 0; fi
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/attakei/yagura:${CI_COMMIT_TAG} .
    - docker push registry.gitlab.com/attakei/yagura:${CI_COMMIT_TAG}

