version: '2'

services:
  app:
    build: .
    user: "${UID}:${GID}"
    volumes:
      - "./var:/app/var"
    ports:
      - "8000:8000"
    env_file: ".env"
    command: sh /app/bin/entry-point.sh web
  cron:
    build: .
    user: "${UID}:${GID}"
    volumes:
      - "./var:/app/var"
    env_file: ".env"
    command: sh /app/bin/entry-point.sh cron
