# Generated by Django 2.0.6 on 2018-07-09 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('enabled', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sites.Site')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together={('site', 'email')},
        ),
    ]
