# Generated by Django 2.0.7 on 2018-08-04 04:17

from django.db import migrations


class Migration(migrations.Migration):
    # For SQLite3 backend: renaming models is not supported
    atomic = False

    dependencies = [
        ('sites', '0002_site_ok_http_status'),
        ('notifications', '0003_deactivation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activation',
            new_name='EmailActivation',
        ),
        migrations.RenameModel(
            old_name='Deactivation',
            new_name='EmailDeactivation',
        ),
        migrations.RenameModel(
            old_name='Recipient',
            new_name='EmailRecipient',
        ),
    ]
