# Generated by Django 2.0.7 on 2018-08-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statehistory',
            name='reason',
            field=models.TextField(default='', verbose_name='Reason of state'),
        ),
    ]
