# Generated by Django 2.1.2 on 2018-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_statehistory_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statehistory',
            name='state',
            field=models.CharField(choices=[('OK', 'OK'), ('NG', 'NG'), ('DISABLED', 'DISABLED')], max_length=10, verbose_name='State label'),
        ),
    ]
