# Generated by Django 2.1.1 on 2018-09-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_ok_http_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Run monitoring?'),
        ),
    ]
