# Generated by Django 2.1.4 on 2019-01-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20190103_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Site name'),
        ),
    ]
